version: '2.1'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start
    volumes:
      - ./files/avatars:/usr/app/public/images/avatars
      - ./files/events:/usr/app/public/images/events
      - ./files/manifestos:/usr/app/public/files/manifestos
      - ./files/uploaded:/usr/app/public/files/uploaded
    ports:
      - 3000:3000
    env_file: .env
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: grey
      DB_USERNAME: grey
      DB_PASSWORD: zYSbtLwTVJt74SRh
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: "postgres:9.5"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: zYSbtLwTVJt74SRh
      POSTGRES_USER: grey
      POSTGRES_DB: grey
    healthcheck:
      test: ["CMD", "psql" ,"-V"]
      timeout: 20s
      retries: 10
