version: '2.1'
services:
  app:
    image: greyjcr/app
    build:
      context: .
    command: npm run start
    volumes:
      - ./files:/usr/app/src/public/files
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3000:3000
    env_file: .env
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: grey
      DB_USERNAME: grey
      DB_PASSWORD: zYSbtLwTVJt74SRh
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy
  postgres:
    image: "postgres:9.5"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: zYSbtLwTVJt74SRh
      POSTGRES_USER: grey
      POSTGRES_DB: grey
    healthcheck:
      test: ["CMD", "psql" ,"-V"]
      timeout: 20s
      retries: 10
  redis:
    image: "redis:3"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./session-data:/data
