version: '2.1'
services:
  migrations:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "npm run migrate-postgres && npm run seed-postgres"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: grey
      DB_USERNAME: postgres
      DB_PASSWORD: 123456
    depends_on:
      postgres:
        condition: service_healthy
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start
    ports:
      - 3000:3000
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: grey
      DB_USERNAME: postgres
      DB_PASSWORD: 123456
    depends_on:
      migrations:
        condition: service_started
      postgres:
        condition: service_healthy
  postgres:
    image: "postgres:9.4"
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: grey
    healthcheck:
      test: ["CMD", "psql" ,"-V"]
      timeout: 20s
      retries: 10
